version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    groups:
      # Arcjet packages are grouped alone due to not being major/minor/patch yet
      arcjet-js:
        patterns:
          - arcjet
          - "@arcjet/*"
